import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StartupLoader from "@/components/startup-loader";
import { WindowProvider } from "@/context/window-manager";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body
        className="relative w-full min-h-screen"
        style={{
          fontFamily: "'Trebuchet MS', Tahoma, Verdana, sans-serif",
          fontSize: 13,
          color: "#1a3a1a",
        }}>
        <WindowProvider>
          <div className="fixed inset-0 -z-10">
            <Image
              src="/img/background.png"
              alt="bg"
              fill
              className="object-cover"
            />
          </div>
          <StartupLoader />

          {children}
        </WindowProvider>
      </body>
    </html>
  );
}
